name: Run tests

on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Check format
        run: npm run format:check

      - name: Run lint
        run: npm run lint

      - name: Check license
        run: npm run license:check

      - name: Run unit tests
        run: npm run test
